services:
  - type: web
    name: server
    env: node
    repo: https://github.com/Shreya-Joshi23/BookStore-Application---MERN
    buildCommand: cd server && npm install
    startCommand: cd server && npm run server
    plan: free

  - type: web
    name: client
    env: static
    repo: https://github.com/Shreya-Joshi23/BookStore-Application---MERN
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    plan: free
